-- MySQL Script generated by MySQL Workbench
-- Fri Feb 18 18:59:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb4 ; 
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincias` (
  `id_provincias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_provincias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localidades` (
  `id_localidades` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `provincias_id` INT NOT NULL,
  PRIMARY KEY (`id_localidades`),
  INDEX `fk_localidades_provincias_idx` (`provincias_id` ASC) ,
  CONSTRAINT `fk_localidades_provincias`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `pizzeria`.`provincias` (`id_provincias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `localidades_id` INT NOT NULL,
  PRIMARY KEY (`id_clientes`),
  INDEX `fk_clientes_localidades1_idx` (`localidades_id` ASC) ,
  CONSTRAINT `fk_clientes_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `pizzeria`.`localidades` (`id_localidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`tienda` (
  `id_tienda` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `cp` VARCHAR(10) NULL,
  `localidades_id` INT NOT NULL,
  PRIMARY KEY (`id_tienda`),
  INDEX `fk_tienda_localidades1_idx` (`localidades_id` ASC) ,
  CONSTRAINT `fk_tienda_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `pizzeria`.`localidades` (`id_localidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`puesto` (
  `id_puesto` INT NOT NULL AUTO_INCREMENT,
  `puesto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_puesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `nif` VARCHAR(20) NULL,
  `telefono` VARCHAR(20) NULL,
  `tienda_id` INT NOT NULL,
  `puesto_id_puesto` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_empleado_tienda1_idx` (`tienda_id` ASC) ,
  INDEX `fk_empleado_puesto1_idx` (`puesto_id_puesto` ASC) ,
  CONSTRAINT `fk_empleado_tienda1`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizzeria`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_puesto1`
    FOREIGN KEY (`puesto_id_puesto`)
    REFERENCES `pizzeria`.`puesto` (`id_puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedidos` (
  `id_pedidos` INT NOT NULL AUTO_INCREMENT,
  `fecha/hora` DATETIME NULL,
  `tipo_pedido` VARCHAR(1) NULL,
  `cantidad_porducto` INT NULL,
  `precio_total` DOUBLE NULL,
  `clientes_id` INT NOT NULL,
  `empleado_repartidor_id` INT NULL,
  `fecha/hora_entrega` DATETIME NULL,
  `tienda_id` INT NOT NULL,
  PRIMARY KEY (`id_pedidos`),
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id` ASC) ,
  INDEX `fk_pedidos_empleado1_idx` (`empleado_repartidor_id` ASC) ,
  INDEX `fk_pedidos_tienda1_idx` (`tienda_id` ASC) ,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `pizzeria`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_empleado1`
    FOREIGN KEY (`empleado_repartidor_id`)
    REFERENCES `pizzeria`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_tienda1`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizzeria`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoria_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria_pizza` (
  `id_categoria_pizza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`tipo` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`productos` (
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `imagen` VARCHAR(50) NULL,
  `precio` INT NULL,
  `categoria_pizza_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`id_productos`),
  INDEX `fk_productos_categoria_pizza1_idx` (`categoria_pizza_id` ASC) ,
  INDEX `fk_productos_tipo1_idx` (`tipo_id` ASC) ,
  CONSTRAINT `fk_productos_categoria_pizza1`
    FOREIGN KEY (`categoria_pizza_id`)
    REFERENCES `pizzeria`.`categoria_pizza` (`id_categoria_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `pizzeria`.`tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedidos_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedidos_productos` (
  `pedidos_id_pedidos` INT NOT NULL,
  `productos_id_productos` INT NOT NULL,
  INDEX `fk_pedidos_productos_pedidos1_idx` (`pedidos_id_pedidos` ASC) ,
  INDEX `fk_pedidos_productos_productos1_idx` (`productos_id_productos` ASC) ,
  PRIMARY KEY (`pedidos_id_pedidos`, `productos_id_productos`),
  CONSTRAINT `fk_pedidos_productos_pedidos1`
    FOREIGN KEY (`pedidos_id_pedidos`)
    REFERENCES `pizzeria`.`pedidos` (`id_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_productos_productos1`
    FOREIGN KEY (`productos_id_productos`)
    REFERENCES `pizzeria`.`productos` (`id_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
