-- MySQL Script generated by MySQL Workbench
-- Fri Feb 18 14:28:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` DEFAULT CHARACTER SET utf8mb4 ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`clientes` (
  `id_clientes` INT(11) NOT NULL,
  `cp` VARCHAR(10) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `clientes_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_clientes`),
  INDEX `fk_clientes_clientes1_idx` (`clientes_id` ASC) ,
  CONSTRAINT `fk_clientes_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `Optica`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Optica`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`empleado` (
  `id_empleado` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Optica`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`proveedor` (
  `id_proveedor` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `fax` VARCHAR(20) NULL DEFAULT NULL,
  `nif` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Optica`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`marca` (
  `id_marca` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `proveedor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_marca`),
  INDEX `fk_marca_proveedor1_idx` (`proveedor_id` ASC) ,
  CONSTRAINT `fk_marca_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `Optica`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Optica`.`tipo_montura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`tipo_montura` (
  `id_tipo_montura` INT(11) NOT NULL,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_montura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Optica`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`venta` (
  `id_venta` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `clientes_id` INT(11) NOT NULL,
  `empleado_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_venta_clientes1_idx` (`clientes_id` ASC) ,
  INDEX `fk_venta_empleado1_idx` (`empleado_id` ASC) ,
  CONSTRAINT `fk_venta_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `Optica`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Optica`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Optica`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`gafas` (
  `id_gafas` INT(11) NOT NULL AUTO_INCREMENT,
  `graduacion_ojo_iz` VARCHAR(2) NULL DEFAULT NULL,
  `graduacion_ojo_der` VARCHAR(2) NULL DEFAULT NULL,
  `color_montura` VARCHAR(10) NULL DEFAULT NULL,
  `color_cristal` VARCHAR(10) NULL DEFAULT NULL,
  `marca_id` INT(11) NOT NULL,
  `tipo_montura_id` INT(11) NOT NULL,
  `venta_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_gafas`),
  INDEX `fk_gafas_marca1_idx` (`marca_id` ASC) ,
  INDEX `fk_gafas_tipo_montura1_idx` (`tipo_montura_id` ASC) ,
  INDEX `fk_gafas_venta1_idx` (`venta_id` ASC) ,
  CONSTRAINT `fk_gafas_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `Optica`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gafas_tipo_montura1`
    FOREIGN KEY (`tipo_montura_id`)
    REFERENCES `Optica`.`tipo_montura` (`id_tipo_montura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gafas_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `Optica`.`venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
